### ISSUE TITLE
[FR] Keep the original text

### ISSUE THREAD

**Issue by wwjCMP** [ckt1031/obsidian-wordwise-plugin#162]
Provide an option to decide whether to keep the original text and then generate content below it.

**Comment by ckt1031** [comment]
Which kind of prompt you want to request this feature, like custom prompts?

**Comment by wwjCMP** [comment]
I think it's a matter of personal usage habits, not specific to any type of prompt. I always hope to compare the original text with the content generated by LLM to evaluate the reasonableness of the modifications.

**Comment by ckt1031** [comment]
So, add a setting that allows you to override default prompt action, such as replacement or insertion, is it ok?

**Comment by wwjCMP** [comment]
> So, add a setting that allows you to override default prompt action, such as replacement or insertion, is it ok?

Yes, that's what I hope for.

**Comment by ckt1031** [comment]
Current temp solution is de-select the text, and it will auto insert text to your cursor position

**Comment by tmsbn** [comment]
Is there an update to this? would love to have an option where the AI inserts the text at the bottom of the note instead of replacing the selection.

**Comment by ckt1031** [comment]
Updates under 1 to 2 days, I will add an additional settings to define the manner or the generation, replace, insert front or insert back.

**Comment by ckt1031** [comment]
Completed
